apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlOVEV3TXpFeQpNVEU1TXpkYUZ3MDBOVEV3TXpFeU1URTVNemRhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDZGZkY3Znb0U2SU85Yi9JQ3UyWEtvVjFyYmUwNTYxa0tUQUhZWUhNZm42TitQSjR6SApFaEphUnpvdGFmVUdLd25nQmNUelhRRVNKTEU4RzRsTmhmaTRNZG1KcW5INFNDd1psUXlQb2U2NjFIMGcvb1hrCkFsTFhkS3lEQlJVZUs5Y0s5V2Z3ekFhcFNkZWhuSUVkYUVNWXJLTGd0LzNMOHNwQ3BFWkE3cWhyKzFja25aaDQKQTRUUWptK2Y1UXR0aDEvczhrWk5DOGUxbVRHZWRlMm1BaldsbDE2Vk1nc2JGMTFPTHZJVnZXYTVjM3gwQW14eQpuZXVjS3pRRkZna1FVYlpvaXFUZ3p1eWtJWWpwTmg1d0tkMFNMMnJwT1FNSlYzWVQwTkZBZDRNd25CZm9CNGFiCkNIM3JLbW1LTmwzTmZRQTAwajNiZnRlbGN1S1NmTndOMW5YZkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlFEZ3g2Z0R3K1lVejJHZlQ3aQpCY2xDRk1PRjdqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFuTU1xQU5wTE81b2R4U2JRNkZRNXUzYXc3cDZYCkFaOG5vcEpoTU9WNzRiRzZqVHF2Sy9vR0FqUUVRTGxiWlF4Tllvd25TaDkxZzBLRGtkeTJFNHdtakVrS1k2NnQKR09QNHljTkhYSHd0OWVyMFFhaHBNOXBVQ01FaW91UXhWTnlYU1gvUUd6bk5ybE54ZW5rQjBDRXNGUnpnZEl5VApsWDZaTTBybzY5NGlySnNBWE90ZUV4NlB2OHlWbENsTXZRdW94d01lQTBCb0VMUitROTNLVWdXc0QzYSt0ajAvCmt4Qmt5YldqTU9LV0R1ZjMreVJtYmtVdjNSdW00QjJ1YU15WW1zeVlkbklJRUQ0c1lMd0JZS1FWR05aODJXSWcKVWVhYjRkYXBlMWd2bGlZejhvRzAyekRwSzFGbXBueTN0TGZkbWsxYWhSbndaQmJJd01yc1M3RmFCZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      server: https://d2b31883-1ae4-475a-b7e3-d558d0ad3f2a.k8s.ondigitalocean.com
    name: do-blr1-thing
contexts:
  - context:
      cluster: do-blr1-thing
      user: do-blr1-thing-admin
    name: do-blr1-thing
current-context: do-blr1-thing
kind: Config
preferences: {}
users:
  - name: do-blr1-thing-admin
    user:
      token: dop_v1_17b5f718afd94ecfb3acb9f02346f4f069b36dadf92639a62af117aa868600f6
